name: declarative_sqlite
description: A dart package for declaratively creating SQLite tables and automatically migrating them.
version: 1.0.1
repository: https://github.com/graknol/declarative_sqlite

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  meta: ^1.11.0
  equatable: ^2.0.5
  uuid: ^4.0.0
  sqflite_common: ^2.5.4+3
  path_provider: ">1.0.0 <2.3.0-beta"
  crypto: ^3.0.6
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.6

flutter: {}
