name: declarative_sqlite
description: A dart package for declaratively creating SQLite tables and automatically migrating them.
version: 1.0.1
repository: https://github.com/graknol/declarative_sqlite

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.1
  meta: ^1.16.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  sqflite_common: ^2.5.6
  path_provider: ^2.1.5
  crypto: ^3.0.6
  collection: ^1.19.1
  async: ^2.13.0
  pool: ^1.5.2
  async_locks: ^4.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

flutter: {}
