name: test_generator
description: A test project for declarative_sqlite_generator
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  declarative_sqlite:
    path: ../declarative_sqlite

dev_dependencies:
  declarative_sqlite_generator:
    path: ../declarative_sqlite_generator
  build_runner: ^2.4.9
  test: ^1.25.2
