name: declarative_sqlite_flutter
description: A Flutter package that provides seamless integration of declarative_sqlite with Flutter widgets, forms, and UI patterns.
version: 1.0.2
repository: https://github.com/graknol/declarative_sqlite

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  declarative_sqlite: ^1.0.2
  sqflite_common: ^2.5.6
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Testing dependencies
  test: ^1.26.2
  mockito: ^5.5.0
  build_runner: ^2.7.1
  sqflite_common_ffi: ^2.3.6

flutter: {}
  # This package is a Flutter library
