name: declarative_sqlite_flutter
description: A Flutter package that provides seamless integration of declarative_sqlite with Flutter widgets, forms, and UI patterns.
version: 1.0.0
publish_to: none
repository: https://github.com/graknol/declarative_sqlite

environment:
  sdk: ^3.5.3
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  declarative_sqlite:
    path: ../declarative_sqlite
  sqflite: ^2.3.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Testing dependencies
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  sqflite_common_ffi: ^2.3.6

flutter:
  {}
  # This package is a Flutter library
