// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by declarative_sqlite_generator

import 'package:declarative_sqlite/declarative_sqlite.dart';

import 'package:demo/post.dart';
import 'package:demo/user.dart';

/// Auto-generated registration for all DbRecord classes
class SqliteFactoryRegistration {
  /// Registers all factory methods for DbRecord classes
  static void registerAllFactories() {
    RecordMapFactoryRegistry.register<Post>((data, db) => Post(data, db));
    RecordMapFactoryRegistry.register<User>((data, db) => User(data, db));
  }
}
