builders:
  declarative_sqlite_generator:
    import: "package:declarative_sqlite_generator/src/builder.dart"
    builder_factories: ["declarativeSqliteGenerator"]
    build_extensions: { ".dart": [".db.dart"] }
    auto_apply: dependents
    build_to: source

  registration_builder:
    import: "package:declarative_sqlite_generator/src/builder.dart"
    builder_factories: ["registrationBuilder"]
    build_extensions: { ".dart": [".reg.dart"] }
    auto_apply: dependents
    build_to: source
