name: declarative_sqlite_generator
description: A build generator that generates data classes for interacting with table rows and view rows from declarative_sqlite schemas.
version: 1.0.2
repository: https://github.com/graknol/declarative_sqlite

environment:
  sdk: ^3.9.2

dependencies:
  # Core build system dependencies
  build: ^4.0.0
  build_config: ^1.2.0
  source_gen: ^4.0.1
  analyzer: ^8.2.0

  # Code generation utilities
  code_builder: ^4.7.0
  dart_style: ^3.0.0

  # Additional required dependencies
  glob: ^2.1.2
  logging: ^1.2.0
  path: ^1.9.1

  # Reference to the main library for schema metadata
  declarative_sqlite: ^1.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_test: ^3.4.0
  sqflite_common_ffi: ^2.3.6 # For examples
