name: ifs_cloud_auth
description: A new Flutter package for IFS Cloud authentication.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
