targets:
  $default:
    builders:
      declarative_sqlite_generator:declarative_sqlite_generator:
        enabled: true
        generate_for:
          - lib/**
      declarative_sqlite_generator:registration_scanner:
        enabled: true
        generate_for:
          - lib/**
      declarative_sqlite_generator:registration_aggregator:
        enabled: true
