import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/defining-a-schema',
        'getting-started/initializing-the-database',
        'getting-started/crud-operations',
      ],
    },
    {
      type: 'category',
      label: 'Core Library',
      items: [
        'core-library/intro',
        'core-library/query-builder',
        'core-library/streaming-queries',
        'core-library/data-modeling',
        'core-library/file-management',
        'core-library/data-synchronization',
      ],
    },
    {
      type: 'category',
      label: 'Flutter Integration',
      items: [
        'flutter-integration/intro',
        'flutter-integration/database-provider',
        'flutter-integration/query-list-view',
      ],
    },
    {
      type: 'category',
      label: 'Generator',
      items: ['generator/intro'],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
