// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by declarative_sqlite_generator

import 'package:declarative_sqlite/declarative_sqlite.dart';

import 'simple_test.dart';

/// Auto-generated registration for all DbRecord classes
class SqliteFactoryRegistration {
  /// Registers all factory methods for DbRecord classes
  static void registerAllFactories() {
    RecordMapFactoryRegistry.register<SimpleUser>((data, db) => SimpleUser(data, db));
  }
}
